"use client";

import { useMemo, useRef, useState } from "react";
import { interfaces, observations, parts, releaseHistory, rules, sources, versionInfo } from "./data";
import { downloadText } from "./storage";

export type BOMLine = { id: string; qty: number; unit: string; status: "Required" | "Preferred" | "Optional" | "Substitute"; note: string };
export type CustomPart = { id: string; name: string; description: string; createdAt: string };

function Heading({ eyebrow, title, body, actions }: { eyebrow: string; title: string; body: string; actions?: React.ReactNode }) {
  return <header className="page-heading split-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{body}</p></div>{actions && <div className="page-actions">{actions}</div>}</header>;
}

function Empty({ title, body, action }: { title: string; body: string; action?: React.ReactNode }) {
  return <div className="empty-state compact"><div className="empty-symbol">◇</div><h3>{title}</h3><p>{body}</p>{action}</div>;
}

function formatValue(value: string | undefined) { return value || "Unknown"; }

export function ExplorerWorkspace({ favoriteIds, compareIds, onOpen, onFavorite, onCompare, onAddToBOM }: {
  favoriteIds: string[];
  compareIds: string[];
  onOpen: (id: string) => void;
  onFavorite: (id: string) => void;
  onCompare: (id: string) => void;
  onAddToBOM: (id: string) => void;
}) {
  const [query, setQuery] = useState("");
  const [domain, setDomain] = useState("All domains");
  const [category, setCategory] = useState("All categories");
  const [sort, setSort] = useState("Name");
  const [page, setPage] = useState(1);
  const pageSize = 40;
  const domains = [...new Set(parts.map((part) => part.domain))].sort();
  const categoryNames = [...new Set(parts.filter((part) => domain === "All domains" || part.domain === domain).map((part) => part.category))].sort();
  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return parts.filter((part) => {
      const haystack = [part.id, part.name, part.shortName, part.domain, part.category, part.subcategory, ...part.aliases, ...Object.values(part.specs)].join(" ").toLowerCase();
      return (!needle || needle.split(/\s+/).every((term) => haystack.includes(term))) &&
        (domain === "All domains" || part.domain === domain) &&
        (category === "All categories" || part.category === category);
    }).sort((a, b) => sort === "Category" ? a.category.localeCompare(b.category) || a.name.localeCompare(b.name) : sort === "Domain" ? a.domain.localeCompare(b.domain) || a.name.localeCompare(b.name) : a.name.localeCompare(b.name));
  }, [query, domain, category, sort]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const safePage = Math.min(page, pageCount);
  const visible = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);
  const reset = () => { setQuery(""); setDomain("All domains"); setCategory("All categories"); setSort("Name"); setPage(1); };
  return <section className="simple-page explorer-page">
    <Heading eyebrow="Complete starter catalog" title="All Components" body={`Explore ${parts.length} electronic, electromechanical, mechanical, material, and consumable starter families in one simple list.`}/>
    <div className="explorer-summary">
      {domains.map((item) => <button key={item} className={domain === item ? "active" : ""} onClick={() => { setDomain(item); setCategory("All categories"); setPage(1); }}><strong>{parts.filter((part) => part.domain === item).length}</strong><span>{item}</span></button>)}
      <button className={domain === "All domains" ? "active" : ""} onClick={() => { setDomain("All domains"); setCategory("All categories"); setPage(1); }}><strong>{parts.length}</strong><span>Everything</span></button>
    </div>
    <div className="explorer-controls">
      <label className="explorer-search"><span>Search every field</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Name, identifier, category, size, alias…" autoComplete="off"/></label>
      <label><span>Domain</span><select value={domain} onChange={(event) => { setDomain(event.target.value); setCategory("All categories"); setPage(1); }}><option>All domains</option>{domains.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label><span>Category</span><select value={category} onChange={(event) => { setCategory(event.target.value); setPage(1); }}><option>All categories</option>{categoryNames.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label><span>Sort</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option>Name</option><option>Category</option><option>Domain</option></select></label>
      <button className="soft-action" onClick={reset}>Reset</button>
    </div>
    <div className="category-jump" aria-label="Quick category filters">
      {categoryNames.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => { setCategory(category === item ? "All categories" : item); setPage(1); }}>{item}<b>{parts.filter((part) => (domain === "All domains" || part.domain === domain) && part.category === item).length}</b></button>)}
    </div>
    <div className="explorer-result-bar"><span><strong>{filtered.length}</strong> matching families</span><span>Page {safePage} of {pageCount}</span></div>
    {visible.length ? (
      <div className="table-panel explorer-table-wrap"><table className="data-table explorer-table"><thead><tr><th>Component family</th><th>Domain</th><th>Category</th><th>Key selection state</th><th>Actions</th></tr></thead><tbody>{visible.map((part) => <tr key={part.id}><td><button className="explorer-part-name" onClick={() => onOpen(part.id)}><small>{part.id}</small><strong>{part.name}</strong><span>{part.subcategory}</span></button></td><td><span className="state-chip">{part.domain}</span></td><td>{part.category}</td><td><strong>{part.verification}</strong><small>{part.utility === null ? "Not yet scored · candidate seed" : "Detailed demonstration passport"}</small></td><td><div className="row-actions"><button className={favoriteIds.includes(part.id) ? "active" : ""} onClick={() => onFavorite(part.id)}>{favoriteIds.includes(part.id) ? "★ Saved" : "☆ Save"}</button><button className={compareIds.includes(part.id) ? "active" : ""} onClick={() => onCompare(part.id)}>Compare</button><button onClick={() => onAddToBOM(part.id)}>+ Project</button></div></td></tr>)}</tbody></table></div>
    ) : (
      <Empty title="No components match" body="Broaden the text search, select another domain, or clear the category filter." action={<button className="action-button" onClick={reset}>Reset explorer</button>}/>
    )}
    {pageCount > 1 && <nav className="explorer-pagination" aria-label="Component pages"><button disabled={safePage === 1} onClick={() => setPage(Math.max(1, safePage - 1))}>Previous</button><span>{(safePage - 1) * pageSize + 1}–{Math.min(safePage * pageSize, filtered.length)} of {filtered.length}</span><button disabled={safePage === pageCount} onClick={() => setPage(Math.min(pageCount, safePage + 1))}>Next</button></nav>}
    <div className="seed-disclaimer"><strong>Broad starter coverage, honest evidence</strong><p>Detailed records are marked separately. The expanded families are candidate seeds: exact variants, scores, sourcing, dimensions, standards, interfaces, and compatibility remain Unknown until evidence and human review are added.</p></div>
  </section>;
}

export function CompareWorkspace({ ids, onRemove, onAddToBOM, onBrowse }: { ids: string[]; onRemove: (id: string) => void; onAddToBOM: (id: string) => void; onBrowse: () => void }) {
  const selected = ids.map((id) => parts.find((part) => part.id === id)).filter(Boolean) as typeof parts;
  const rows = useMemo(() => {
    const specNames = [...new Set(selected.flatMap((part) => Object.keys(part.specs)))];
    return ["Domain", "Category", "Verification", "Confidence", "Prototype utility", "Observed commonness", "Interfaces", "Design stages", ...specNames];
  }, [selected]);
  const valueFor = (part: (typeof parts)[number], row: string) => {
    if (row === "Domain") return part.domain; if (row === "Category") return part.category; if (row === "Verification") return part.verification;
    if (row === "Confidence") return part.confidence; if (row === "Prototype utility") return part.utility === null ? "Unknown — not yet scored" : `${part.utility} / 100 — demo`;
    if (row === "Observed commonness") return part.commonness === null ? "Unknown — not yet scored" : `${part.commonness} / 100 — demo`; if (row === "Interfaces") return part.interfaces.map((id) => interfaces.find((item) => item.id === id)?.name).filter(Boolean).join(", ") || "None recorded";
    if (row === "Design stages") return part.stages.join(", "); return formatValue(part.specs[row]);
  };
  return <section className="simple-page"><Heading eyebrow="Maker workbench" title="Compare" body="Place up to four families side by side. Differences are emphasized; equal values stay quiet." actions={<button className="action-button" onClick={onBrowse}>+ Add parts</button>}/>
    {!selected.length ? <Empty title="Nothing to compare yet" body="Choose Compare on any catalog card. CHANDLER will preserve the set locally." action={<button className="action-button" onClick={onBrowse}>Browse catalog</button>}/> : <div className="compare-wrap"><table className="data-table compare-table"><thead><tr><th>Attribute</th>{selected.map((part) => <th key={part.id}><small>{part.id}</small><strong>{part.shortName}</strong><button onClick={() => onRemove(part.id)}>Remove</button></th>)}</tr></thead><tbody>{rows.map((row) => { const values = selected.map((part) => valueFor(part,row)); const differs = new Set(values).size > 1; return <tr key={row} className={differs ? "different" : "same"}><th>{row}{differs && <span>Different</span>}</th>{values.map((value,index) => <td key={`${row}-${selected[index].id}`}>{value}</td>)}</tr>; })}<tr className="compare-actions"><th>Project</th>{selected.map((part) => <td key={part.id}><button onClick={() => onAddToBOM(part.id)}>Add to project</button></td>)}</tr></tbody></table><div className="comparison-note"><strong>Compatibility note</strong><p>Matching labels or nominal sizes are not proof of interchangeability. Class A and Class B mechanical substitutions require human review and documented constraints.</p></div></div>}
  </section>;
}

function bomExports(lines: BOMLine[]) {
  const enriched = lines.map((line) => ({ ...line, part: parts.find((part) => part.id === line.id) }));
  return {
    json: JSON.stringify({ application: "CHANDLER", applicationVersion: versionInfo.application, catalogVersion: versionInfo.catalog, schemaVersion: versionInfo.schema, exportedAt: new Date().toISOString(), project: { id: "PROJECT-BENCH-SUPPLY", name: "Bench Supply", lines: enriched.map(({ part, ...line }) => ({ ...line, selectedRevision: { id: part?.id, name: part?.name, catalogVersion: versionInfo.catalog, specifications: part?.specs } })) } }, null, 2),
    csv: ["Part ID,Name,Quantity,Unit,Status,Note", ...enriched.map(({ part, ...line }) => [line.id, part?.name ?? "Unknown", line.qty, line.unit, line.status, line.note].map((cell) => `"${String(cell).replaceAll('"','""')}"`).join(","))].join("\n"),
    markdown: [`# Bench Supply — CHANDLER Project BOM`, "", `Generated: ${new Date().toLocaleString()}`, `Catalog: ${versionInfo.catalog} · Schema: ${versionInfo.schema}`, "", "| Part | Quantity | Status | Note |", "|---|---:|---|---|", ...enriched.map(({ part, ...line }) => `| ${part?.name ?? line.id} | ${line.qty} ${line.unit} | ${line.status} | ${line.note || "—"} |`), "", "> Verify all dimensions, ratings, standards, and supplier facts before design release."].join("\n"),
  };
}

export function BOMWorkspace({ lines, setLines, notify, onBrowse }: { lines: BOMLine[]; setLines: React.Dispatch<React.SetStateAction<BOMLine[]>>; notify: (message: string) => void; onBrowse: () => void }) {
  const exports = bomExports(lines);
  const setLine = (id: string, patch: Partial<BOMLine>) => setLines((current) => current.map((line) => line.id === id ? { ...line, ...patch } : line));
  const exportFile = (kind: "json" | "csv" | "markdown") => { const ext = kind === "markdown" ? "md" : kind; const mime = kind === "json" ? "application/json" : kind === "csv" ? "text/csv" : "text/markdown"; downloadText(`chandler-bench-supply.${ext}`, exports[kind], mime); notify(`${kind.toUpperCase()} project BOM downloaded`); };
  const baseline = () => { downloadText(`chandler-baseline-${new Date().toISOString().slice(0,10)}.json`, exports.json, "application/json"); notify("Immutable project snapshot downloaded"); };
  return <section className="simple-page"><Heading eyebrow="Project workspace" title="Bench Supply" body="Assemble a working Bill of Materials (BOM), capture intent, and lock the selected catalog state into a project baseline." actions={<><button className="soft-action" onClick={onBrowse}>Add from catalog</button><button className="action-button" onClick={baseline}>Create baseline</button></>}/>
    <div className="project-summary"><div><small>Project ID</small><strong>PROJECT-BENCH-SUPPLY</strong></div><div><small>Lines</small><strong>{lines.length}</strong></div><div><small>Total quantity</small><strong>{lines.reduce((sum,line) => sum + line.qty,0)}</strong></div><div><small>Catalog locked</small><strong>{versionInfo.catalog}</strong></div></div>
    {!lines.length ? <Empty title="This project bench is empty" body="Add a recommended family or an exact variant from Discover." action={<button className="action-button" onClick={onBrowse}>Find parts</button>}/> : <div className="table-panel"><div className="table-scroll"><table className="data-table bom-table"><thead><tr><th>Part</th><th>Qty</th><th>Unit</th><th>Intent</th><th>Notes</th><th>Action</th></tr></thead><tbody>{lines.map((line) => { const part = parts.find((item) => item.id === line.id); return <tr key={line.id}><td><small>{line.id}</small><strong>{part?.name ?? "Unknown part"}</strong><span>{part?.verification ?? "Unknown state"}</span></td><td><input type="number" min="0" step="1" value={line.qty} onChange={(event) => setLine(line.id,{qty:Math.max(0,Number(event.target.value))})}/></td><td><select value={line.unit} onChange={(event) => setLine(line.id,{unit:event.target.value})}><option>each</option><option>set</option><option>meter</option><option>millimeter</option></select></td><td><select value={line.status} onChange={(event) => setLine(line.id,{status:event.target.value as BOMLine["status"]})}><option>Required</option><option>Preferred</option><option>Optional</option><option>Substitute</option></select></td><td><input value={line.note} onChange={(event) => setLine(line.id,{note:event.target.value})} placeholder="Assembly location, designator, alternative…"/></td><td><button className="danger-link" onClick={() => setLines((current) => current.filter((item) => item.id !== line.id))}>Remove</button></td></tr>; })}</tbody></table></div>
      <div className="export-bar"><span>Export with application, catalog, and schema versions</span><button onClick={() => exportFile("json")}>JSON</button><button onClick={() => exportFile("csv")}>CSV</button><button onClick={() => exportFile("markdown")}>Markdown</button><button onClick={() => window.print()}>Print report</button></div></div>}
  </section>;
}

export function MyPartsWorkspace({ favoriteIds, stock, setStock, notes, setNotes, customParts, setCustomParts, onOpen }: { favoriteIds: string[]; stock: Record<string,number>; setStock: React.Dispatch<React.SetStateAction<Record<string,number>>>; notes: Record<string,string>; setNotes: React.Dispatch<React.SetStateAction<Record<string,string>>>; customParts: CustomPart[]; setCustomParts: React.Dispatch<React.SetStateAction<CustomPart[]>>; onOpen: (id: string) => void }) {
  const [showForm,setShowForm] = useState(false), [name,setName] = useState(""), [description,setDescription] = useState("");
  const addCustom = () => { if (!name.trim()) return; setCustomParts((current) => [...current,{id:`LOCAL-${Date.now()}`,name:name.trim(),description:description.trim(),createdAt:new Date().toISOString()}]); setName("");setDescription("");setShowForm(false); };
  const favorites = favoriteIds.map((id) => parts.find((part) => part.id === id)).filter(Boolean) as typeof parts;
  return <section className="simple-page"><Heading eyebrow="Local overlay" title="My Parts" body="Favorites, shelf quantities, notes, and custom records stay on this device and remain separate from the common catalog." actions={<button className="action-button" onClick={() => setShowForm((open) => !open)}>+ Custom part</button>}/>
    {showForm && <div className="inline-form"><label>Part name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Custom bracket, cable assembly…"/></label><label>Description<input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What it is and why you use it"/></label><button onClick={addCustom} disabled={!name.trim()}>Save local part</button><button className="text-button" onClick={() => setShowForm(false)}>Cancel</button></div>}
    <div className="section-divider"><span>Saved catalog families</span><b>{favorites.length}</b></div>
    {!favorites.length ? <Empty title="No favorites yet" body="Use the star on a catalog card or Part Passport to keep reliable starting points close."/> : <div className="local-parts-grid">{favorites.map((part) => <article key={part.id}><div><small>{part.id}</small><button className="part-link" onClick={() => onOpen(part.id)}>{part.name}</button><span>{part.category}</span></div><label>On shelf<input type="number" min="0" value={stock[part.id] ?? 0} onChange={(event) => setStock((current) => ({...current,[part.id]:Math.max(0,Number(event.target.value))}))}/></label><label>Local note<textarea rows={2} value={notes[part.id] ?? ""} onChange={(event) => setNotes((current) => ({...current,[part.id]:event.target.value}))} placeholder="Bin, preferred finish, supplier…"/></label></article>)}</div>}
    <div className="section-divider"><span>Custom local records</span><b>{customParts.length}</b></div>
    {!customParts.length ? <p className="quiet-line">Custom parts will appear here and will never be mixed into the published catalog.</p> : <div className="custom-list">{customParts.map((part) => <article key={part.id}><div><small>{part.id}</small><strong>{part.name}</strong><p>{part.description || "No description"}</p></div><button className="danger-link" onClick={() => setCustomParts((current) => current.filter((item) => item.id !== part.id))}>Delete</button></article>)}</div>}
  </section>;
}

export function UpdatesWorkspace({ onBackup, onRestore, onFreshStart, notify }: { onBackup: () => void; onRestore: (file: File) => void; onFreshStart: () => void; notify: (message: string) => void }) {
  const input = useRef<HTMLInputElement>(null);
  return <section className="simple-page"><Heading eyebrow="Catalog operations" title="Catalog Updates" body="Application, catalog, and schema versions move independently. Updates never silently rewrite a project baseline." actions={<button className="action-button" onClick={() => notify("No remote update address is configured. Import a signed catalog package instead.")}>Check for updates</button>}/>
    <div className="version-board"><article className="active-release"><span>Active catalog</span><h2>{versionInfo.catalog}</h2><p>Bundled starter package</p><div><b>Schema {versionInfo.schema}</b><b>{parts.length} families</b><b>Checksum: development package</b></div></article><article><span>Application</span><h2>v{versionInfo.application}</h2><p>Local-first public workbench</p></article><article><span>Freshness</span><h2>Seed coverage</h2><p>Candidate scores, supplier facts, and real census counts are Unknown.</p></article></div>
    <div className="update-flow"><div><span>1</span><strong>Validate</strong><small>Schema and manifest</small></div><i/><div><span>2</span><strong>Checkpoint</strong><small>Preserve current state</small></div><i/><div><span>3</span><strong>Migrate</strong><small>Preview changes</small></div><i/><div><span>4</span><strong>Activate</strong><small>Keep rollback copy</small></div></div>
    <div className="operations-grid"><article><h3>Workspace backup</h3><p>Export catalog-independent user data, projects, notes, local stock, settings, and review decisions.</p><button onClick={onBackup}>Download full backup</button></article><article><h3>Restore or migrate</h3><p>Import a CHANDLER backup. Validation runs against a copy before local state is replaced.</p><input ref={input} hidden type="file" accept="application/json,.json" onChange={(event) => { const file=event.target.files?.[0]; if(file) onRestore(file); event.currentTarget.value=""; }}/><button onClick={() => input.current?.click()}>Choose backup JSON</button></article><article><h3>Fresh Start</h3><p>Clear user-created local workspace data and return to the demonstration catalog. This cannot be undone without a backup.</p><button className="danger-button" onClick={onFreshStart}>Clear local workspace</button></article></div>
    <div className="release-list"><div className="section-divider"><span>Recovery checkpoints</span><b>{releaseHistory.length}</b></div>{releaseHistory.map((release) => <article key={release.version}><span className={`state-chip ${release.state.toLowerCase()}`}>{release.state}</span><div><strong>{release.version}</strong><small>{release.date} · {release.families} families · {release.observations} observations</small></div><p>{release.note}</p><button onClick={() => release.state === "Active" ? notify("This catalog is already active") : notify(`Rollback preview ready for ${release.version}; no data changed`)}>{release.state === "Active" ? "Current" : "Preview rollback"}</button></article>)}</div>
  </section>;
}

export function HelpWorkspace() {
  return <section className="simple-page"><Heading eyebrow="Methodology & trust" title="Help" body="CHANDLER is a starting-point library, not a substitute for engineering verification."/>
    <div className="help-grid"><article><span>01</span><h3>Common is not recommended</h3><p>Observed Commonness measures presence across independent projects. Prototype Utility measures sourcing resilience, interchangeability, assembly effort, documentation, cost suitability, and reuse.</p></article><article><span>02</span><h3>Interfaces first</h3><p>A nominal size is only the beginning. Fit, tolerance, rating, ecosystem, mating definition, tooling, and environment determine whether two parts really work together.</p></article><article><span>03</span><h3>Unknown means unknown</h3><p>CHANDLER never turns missing evidence into a zero or a dash. Demonstration records label synthetic scores, while stock and price remain explicitly Unknown.</p></article><article><span>04</span><h3>Your work stays local</h3><p>Favorites, projects, stock, notes, and custom parts are saved on this device. There is no telemetry, advertising, mandatory account, or hidden network activity.</p></article></div>
    <div className="method-panel"><h2>Recommended workflow</h2><div className="method-flow"><span>Discover</span><i>→</i><span>Compare</span><i>→</i><span>Select</span><i>→</i><span>Source</span><i>→</i><span>Use</span><i>→</i><span>Verify</span><i>→</i><span>Share</span></div><p>Before committing a design, review the manufacturer datasheet or drawing, applicable standard, tolerances, load calculations, safety requirements, environmental constraints, and the exact supplier offer.</p></div>
  </section>;
}

export function CuratorWorkspace({ active, decisions, setDecisions, notify }: { active: string; decisions: Record<string,string>; setDecisions: React.Dispatch<React.SetStateAction<Record<string,string>>>; notify: (message:string) => void }) {
  const [paste,setPaste] = useState("M3x8 SHCS\t24\teach\n608ZZ\t4\teach\n2020 V-slot rail 500mm\t6\tlength");
  const [imported,setImported] = useState(false), [ruleTest,setRuleTest] = useState("DIN 912 M3x8"), [proposalType,setProposalType] = useState("Correction"), [proposalText,setProposalText] = useState(""), [proposalSource,setProposalSource] = useState("");
  const preview = paste.split(/\r?\n/).filter(Boolean).map((line,index) => { const cells=line.split(/\t|,/); return {id:`PREVIEW-${index+1}`,description:cells[0]?.trim()||"",qty:cells[1]?.trim()||"Unknown",unit:cells[2]?.trim()||"Unknown"}; });
  const decide = (id:string,decision:string) => { setDecisions((current) => ({...current,[id]:decision})); notify(`${id}: ${decision}`); };
  if (active === "curator-home") return <section className="simple-page"><Heading eyebrow="Catalog maintenance" title="Curator Overview" body="Collect, extract, normalize, review, publish, and update without modifying raw evidence."/>
    <div className="curator-kpis"><article><small>Review queue</small><strong>{observations.filter((item)=>!decisions[item.id] && item.state==="Review").length}</strong><span>candidate matches</span></article><article><small>Sources ready</small><strong>{sources.filter((item)=>item.status==="Ready").length}</strong><span>of {sources.length} adapters</span></article><article><small>Canonical families</small><strong>{parts.length}</strong><span>demonstration records</span></article><article><small>Quality gates</small><strong>18/18</strong><span>sample package checks</span></article></div>
    <div className="pipeline-board"><div><b>Raw observations</b><strong>{observations.length}</strong><small>Immutable evidence</small></div><i>→</i><div><b>Candidate clusters</b><strong>4</strong><small>Automation proposes</small></div><i>→</i><div><b>Human review</b><strong>{Object.keys(decisions).length}</strong><small>Decisions captured</small></div><i>→</i><div><b>Published catalog</b><strong>{parts.length}</strong><small>Validated families</small></div></div>
    <div className="curator-columns"><article><h3>Attention needed</h3>{observations.filter((item)=>item.state==="Review").map((item)=><button key={item.id} onClick={()=>notify(`${item.id}: “${item.original}” at ${Math.round(item.confidence*100)}% confidence`)}><span className="state-chip review">Review</span><strong>{item.original}</strong><small>{item.id} · {Math.round(item.confidence*100)}% candidate confidence</small></button>)}</article><article><h3>Operating cadence</h3><dl><div><dt>Weekly</dt><dd>Import projects and check broken sources</dd></div><div><dt>Monthly</dt><dd>Review aliases, conflicts, and clusters</dd></div><div><dt>Quarterly</dt><dd>Recalculate scores and sourcing resilience</dd></div><div><dt>Annually</dt><dd>Publish methodology and major baseline</dd></div></dl></article></div>
  </section>;
  if (active === "sources") return <section className="simple-page"><Heading eyebrow="Evidence registry" title="Sources" body="Each adapter is isolated, versioned, and governed by terms, licensing, attribution, and rate-limit status." actions={<button className="action-button" onClick={()=>notify("Local manual import adapter is ready")}>Run ready adapters</button>}/><div className="source-grid">{sources.map((source)=><article key={source.id}><header><span className={`state-chip ${source.status.toLowerCase()}`}>{source.status}</span><code>{source.id}</code></header><h3>{source.name}</h3><dl><div><dt>Access</dt><dd>{source.method}</dd></div><div><dt>Terms</dt><dd>{source.terms}</dd></div><div><dt>License</dt><dd>{source.license}</dd></div><div><dt>Last import</dt><dd>{source.last}</dd></div></dl><button onClick={()=>notify(`${source.name}: adapter check completed; no remote request made`)}>Check adapter</button></article>)}</div></section>;
  if (active === "imports") return <section className="simple-page"><Heading eyebrow="Local ingestion" title="Manual Import" body="Paste comma- or tab-separated BOM lines, preview the mapping, and validate before creating immutable observations."/><div className="import-layout"><article><label>Paste BOM lines<textarea rows={12} value={paste} onChange={(event)=>{setPaste(event.target.value);setImported(false)}}/></label><p>Mapped columns: Description · Quantity · Unit</p><div><button className="action-button" onClick={()=>setImported(true)} disabled={!preview.length}>Validate and stage {preview.length}</button><button className="soft-action" onClick={()=>{setPaste("");setImported(false)}}>Clear</button></div></article><article><div className="section-divider"><span>Preview</span><b>{preview.length} rows</b></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>State</th></tr></thead><tbody>{preview.map((row)=><tr key={row.id}><td>{row.description}</td><td>{row.qty}</td><td>{row.unit}</td><td><span className={`state-chip ${imported?"ready":"draft"}`}>{imported?"Staged":"Preview"}</span></td></tr>)}</tbody></table></div>{imported&&<div className="success-panel"><strong>Validation passed</strong><p>{preview.length} rows are staged in a temporary import. Canonical records have not been changed.</p><button onClick={()=>notify(`Created ${preview.length} local demonstration observations`)}>Commit observations</button></div>}</article></div></section>;
  if (active === "review") return <section className="simple-page"><Heading eyebrow="Delta review" title="Review Queue" body="Automation proposes; a human accepts, rejects, defers, edits, merges, splits, or requests evidence."/><div className="review-list">{observations.map((item)=>{const candidate=parts.find((part)=>part.id===item.candidate);return <article key={item.id} className={decisions[item.id]?"decided":""}><header><span className={`state-chip ${item.state.toLowerCase()}`}>{decisions[item.id]||item.state}</span><code>{item.id}</code><b>{Math.round(item.confidence*100)}% confidence</b></header><div className="review-map"><div><small>Original immutable text</small><strong>{item.original}</strong><span>{item.qty} {item.unit} · {item.project}</span></div><i>→</i><div><small>Suggested family</small><strong>{candidate?.name??"No candidate"}</strong><span>{item.candidate}</span></div></div><footer>{["Accept","Reject","Defer","Request evidence"].map((decision)=><button key={decision} onClick={()=>decide(item.id,decision)}>{decision}</button>)}</footer></article>})}</div></section>;
  if (active === "canonical") return <section className="simple-page"><Heading eyebrow="Curator-controlled layer" title="Canonical Parts" body="Stable families and reusable interfaces remain separate from volatile supplier offers."/><div className="table-panel"><table className="data-table canonical-table"><thead><tr><th>Identifier</th><th>Family</th><th>Domain</th><th>State</th><th>Confidence</th><th>Interfaces</th></tr></thead><tbody>{parts.map((part)=><tr key={part.id}><td><code>{part.id}</code></td><td><strong>{part.name}</strong><small>{part.subcategory}</small></td><td>{part.domain}</td><td><span className={`state-chip ${part.verification.toLowerCase().replace(" ","-")}`}>{part.verification}</span></td><td>{part.confidence}</td><td>{part.interfaces.length}</td></tr>)}</tbody></table></div></section>;
  if (active === "rules") { const normalized=ruleTest.replace(/din\s*912/ig,"ISO 4762 geometry reference").replace(/m3\s*[x×]\s*8/ig,"M3 × 8 millimeters").replace(/shcs/ig,"socket-head cap screw").replace(/608zz/ig,"608 bearing + dual metal shields"); return <section className="simple-page"><Heading eyebrow="Deterministic engine" title="Normalization Rules" body="Rules are versioned, testable, reversible, and applied to candidates—not directly to canonical records."/><div className="rule-tester"><label>Test an original BOM description<input value={ruleTest} onChange={(event)=>setRuleTest(event.target.value)}/></label><div><small>Normalized preview</small><strong>{normalized||"Enter source text"}</strong><span>No record changed</span></div></div><div className="table-panel"><table className="data-table"><thead><tr><th>Rule</th><th>Type</th><th>Pattern</th><th>Transformation</th><th>Scope</th><th>Version</th><th>State</th></tr></thead><tbody>{rules.map((rule)=><tr key={rule.id}><td><code>{rule.id}</code></td><td>{rule.type}</td><td>{rule.pattern}</td><td>{rule.replacement}</td><td>{rule.scope}</td><td>{rule.version}</td><td><span className={`state-chip ${rule.state.toLowerCase()}`}>{rule.state}</span></td></tr>)}</tbody></table></div></section>; }
  if (active === "quality") return <section className="simple-page"><Heading eyebrow="Validation gates" title="Quality Dashboard" body="A published package must preserve identifiers, provenance, interfaces, scores, assets, migrations, and checksums."/><div className="quality-summary"><div><strong>100%</strong><span>Sample package checks passed</span></div><ul><li><b>0</b> duplicate permanent identifiers</li><li><b>0</b> orphan interface references</li><li><b>0</b> negative quantities</li><li><b>0</b> circular replacements</li><li><b>0</b> missing Unknown states</li><li><b>0</b> silent migration losses</li></ul></div><div className="quality-gates">{["Schema and manifest","Permanent identifiers","Family-to-interface links","Source provenance","Asset license states","Score inputs","Migration fixtures","Checksum verification","Offline package"].map((gate)=><article key={gate}><span>✓</span><strong>{gate}</strong><small>Passed for demonstration package</small></article>)}</div></section>;
  if (active === "releases") return <section className="simple-page"><Heading eyebrow="Governance & publishing" title="Catalog Releases" body="Review a delta, generate a package, validate its manifest, and preserve rollback before publication." actions={<button className="action-button" onClick={()=>notify("Release candidate manifest generated locally")}>Prepare release candidate</button>}/><div className="release-timeline">{releaseHistory.map((release,index)=><article key={release.version}><span>{index+1}</span><div><small>{release.date}</small><h3>{release.version}</h3><p>{release.note}</p><dl><div><dt>Families</dt><dd>{release.families}</dd></div><div><dt>Observations</dt><dd>{release.observations}</dd></div><div><dt>State</dt><dd>{release.state}</dd></div></dl></div><button onClick={()=>downloadText(`chandler-release-${release.version}.json`,JSON.stringify({manifest:{catalogVersion:release.version,schemaVersion:versionInfo.schema,generatedAt:new Date().toISOString(),partFamilyCount:release.families,observationCount:release.observations,checksumAlgorithm:"SHA-256",checksum:"development-package"},release},null,2),"application/json")}>Export manifest</button></article>)}</div><div className="audit-panel"><div className="section-divider"><span>Recent audit events</span><b>{Object.keys(decisions).length+2}</b></div><p><code>AUD-DEMO-001</code> Demonstration catalog activated · 2026-08-24</p><p><code>AUD-DEMO-002</code> Schema 3 validation completed · 2026-08-24</p>{Object.entries(decisions).map(([id,decision],index)=><p key={id}><code>AUD-LOCAL-{String(index+3).padStart(3,"0")}</code> {id} marked {decision} · local session</p>)}</div></section>;
  if (active === "proposals") return <section className="simple-page"><Heading eyebrow="Community contribution" title="Proposal Builder" body="Prepare a structured change request locally, then export JSON for submission without an account or configured server."/><div className="proposal-form"><label>Proposal type<select value={proposalType} onChange={(event)=>setProposalType(event.target.value)}>{["New family","New variant","New supplier reference","Correction","New alias","New interface","Compatibility claim","Deprecation recommendation","Broken-link report","Safety concern","Additional project evidence"].map((item)=><option key={item}>{item}</option>)}</select></label><label>Proposed change<textarea rows={5} value={proposalText} onChange={(event)=>setProposalText(event.target.value)} placeholder="Describe the change, dimensions, units, use case, and limitations…"/></label><label>Supporting source<input value={proposalSource} onChange={(event)=>setProposalSource(event.target.value)} placeholder="Source address or citation"/></label><button className="action-button" disabled={!proposalText.trim()} onClick={()=>downloadText("chandler-community-proposal.json",JSON.stringify({schemaVersion:versionInfo.schema,type:proposalType,proposedChange:proposalText,supportingSource:proposalSource||"Not supplied",createdAt:new Date().toISOString(),state:"Proposed"},null,2),"application/json")}>Export proposal JSON</button></div></section>;
  return null;
}
